### PR TITLE
liquid_tags: Switch SoundCloud API links from http to https

### PR DESCRIPTION
**Pull request by xsteadfastx**
the soundcloud api doesnt listen on http anymore.

### CODE REVIEW

**Comment by justinmayer** [comment]
Many thanks for the contribution, @xsteadfastx. There appear to be some conflicts, most likely because I merged other PRs that touched the same lines. Would you be so kind as to resolve the conflicts and rebase on latest master? Many thanks! 😅

**Comment by xsteadfastx** [comment]
thats just strange... cause im the last one edited that file with a commit 4 years ago. how can that conflict? i really have no idea ;-)

**Comment by Lucas-C** [comment]
Because we are currently using `nose` to run the tests in this repo, I had to to edit this plugins tests in this commit : https://github.com/getpelican/pelican-plugins/commit/3040e2f12592617447b07fe72b21563392d17562#diff-5758f0e505c02ffd069e994491272e1b

**Comment by xsteadfastx** [comment]
done the rebase!

**Comment by Lucas-C** [comment]
Seems like the tests don't pass

From Travis CI:
```
TypeError: test_match_it() missing 2 required positional arguments: 'input' and 'expected'

TypeError: test_match_it_exception() missing 1 required positional argument: 'input'
```

**Comment by xsteadfastx** [comment]
> Seems like the tests don't pass
> 
> From Travis CI:
> 
> ```
> TypeError: test_match_it() missing 2 required positional arguments: 'input' and 'expected'
> 
> TypeError: test_match_it_exception() missing 1 required positional argument: 'input'
> ```

this is some strange nose and pytest problem. you just can run the tests fine with `pytest test_soundcloud.py` and everything runs fine. so what can we do about it?

**Comment by Lucas-C** [comment]
Ok I see. The you should preserve those initial lines that were at the top of the test file:
```python
if 'nosetests' in sys.argv[0]:
    raise unittest.SkipTest('Those tests are pytest-compatible only')
```

**Comment by xsteadfastx** [comment]
> Ok I see. The you should preserve those initial lines that were at the top of the test file:
> 
> ```python
> if 'nosetests' in sys.argv[0]:
>     raise unittest.SkipTest('Those tests are pytest-compatible only')
> ```

done

**Comment by justinmayer** [comment]
Many thanks to @xsteadfastx for the fix and to @Lucas-C for reviewing. 👍

**Pull request merged**
