### PR TITLE
Added support for attached images

### PR DESCRIPTION
**Pull request by mitchins**
Current implementation did not work with {attach} ( or even images without an absolute path), because:
1. Assumed the item existed at output already
2. Could not deal with {attach} in name, did not remove and threw warning

The solution:

Does not assume file path is absolute, and does not require image to be copied yet.

If detects {attach} in filename-only then it will look relative to the current data file (.md for example) for reading properties.

 **Otherwise maintains the way it works now, have tested with data for example and the conditional only triggers when {attach} is seen, all else is as per existing.**

### CODE REVIEW

**Comment by mitchins** [comment]
@justinmayer I think this goes to you normally.

**Comment by justinmayer** [comment]
Hi Mitchell. Is there a reason you closed this pull request? Also, it seems the source repository has disappeared.

**Comment by mitchins** [comment]
Thanks Justin,
There should be a newer one.
I didn’t realise I originally created it on a pull request I made 6 months ago hence it was out of date! Do you see the new one? (Should be #956)

Better safe than sorry, so I checked out a fresh copy, as I’m not sure how to rebase on GitHub with forks)

**Comment by mitchins** [comment]
https://github.com/getpelican/pelican-plugins/pull/956

**Pull request closed without merging**
