### PR TITLE
Headerid

### PR DESCRIPTION
**Pull request by ionelmc**

### CODE REVIEW

**Comment by justinmayer** [comment]
Hi Ionel. Are you targeting Markdown? If so, I believe Python-Markdown supports this already via its [TOC extension](https://pythonhosted.org/Markdown/extensions/toc.html).

I'm less familiar with reST, but I believe it also supports header ID generation.

**Comment by ionelmc** [comment]
Hey @justinmayer, this is for reStructuredText. And no, it doesn't have any builtin headerid thing, unlike some of the markdown libs. You can see it in action [here](http://blog.ionelmc.ro).

**Comment by justinmayer** [comment]
Oh, I see now that you did indeed mention that in the ReadMe commit. Thanks!

**Comment by justinmayer** [comment]
Clarified things a bit in the README via f7174a2.

**Pull request merged**
