### PR TITLE
PlantUML: add support for Markdown syntax

### PR DESCRIPTION
**Pull request by mikitex70**
* added support for Markdown syntax
* fixed some incompatibility with python 3.4
* added a filter to use plantuml with pandoc up to 1.16.0 excluded.

### CODE REVIEW

**Comment by justinmayer** [comment]
Could you [rebase & squash](https://github.com/getpelican/pelican/wiki/Git-Tips#squashing-commits) into semantically discrete commits? There are a bunch of upstream merge commits in here that don't add anything useful to the commit history.

**Comment by mikitex70** [comment]
Thanks for your suggestion.
Done some squash in the commits and rebased.

**Comment by justinmayer** [comment]
Thanks, Michele. Though there still appears to be a merge commit in this PR: 02555f9

**Comment by mikitex70** [comment]
I think now the commits are ok.
Excuse me for the commit branch, but I need more experience on working on github :-)

**Comment by justinmayer** [comment]
Bravissimo! I totally understand that Git can sometimes be a confusing tool (for me, too). Thanks again for the enhancements, Michele!  (^_^)

**Pull request merged**
