### PR TITLE
Update the JINJA_ENVIRONMENT  description 

### PR DESCRIPTION
**Pull request by jadjay**
The new pelican doesn't use JINJA_EXTENSIONS anymore,

Please update with JINJA_ENVIRONMENT in place

### CODE REVIEW

**Comment by justinmayer** [comment]
Thank you for the contribution, @jadjay. I think it's better if we replace the previous instructions entirely with the new setting (that is, removing references to `JINJA_EXTENSIONS`, etc). Would you please make those changes and then [squash your commits](https://github.com/getpelican/pelican/wiki/Git-Tips#squashing-commits)?

**Comment by jadjay** [comment]
Hope is it okay I tried to follow the squash howto,

**Comment by jadjay** [comment]
By the way you must do something about your DNS :)
selection_114
selection_113

**Comment by justinmayer** [comment]
This PR has presumably been obviated by your subsequent PR.

**Pull request closed without merging**
