### PR TITLE
Liquidtags notebook support ipython3

### LINKED ISSUE #427: liquid_tags.notebook: IPython 3.0 not supported
On IPython 3.0, which was released a few days ago, I get the following error when I run `make html`.

Note that `python/ipython-nb-plotting.md` contains the following:

```
Title: Plotting in IPython Notebook
Date: 2010-12-03 10:20
Modified: 2010-12-05 19:30
Category: Python
Tags: pelican, publishing
Slug: my-super-post
Authors: Alexis Metaireau, Conan Doyle
Summary: Short version for index and feeds

Hiya!

{% notebook Untitled.ipynb %}
```

and `Untitled.ipynd` is in `content/notebooks`.

This works fine for IPython 2.4 which is the previous version.

```
DEBUG: Successfully loaded extension "liquid_tags.mdx_liquid_tags.LiquidTags".
DEBUG: Successfuly imported extension module "markdown.extensions.meta".
DEBUG: Successfully loaded extension "markdown.extensions.meta.MetaExtension".
/Users/tiao/.virtualenvs/blog/lib/python2.7/site-packages/IPython/nbformat/current.py:75: UserWarning: reads_json is deprecated, use reads
  warnings.warn("reads_json is deprecated, use reads")
DEBUG: Applying preprocessor: coalesce_streams
ERROR: Could not process python/ipython-nb-plotting.md
  | cells
  |___
  | Traceback (most recent call last):
  |   File "/Users/tiao/.virtualenvs/blog/lib/python2.7/site-packages/pelican/generators.py", line 502, in generate_context
  |     context_sender=self)
  |   File "/Users/tiao/.virtualenvs/blog/lib/python2.7/site-packages/pelican/readers.py", line 459, in read_file
  |     content, reader_metadata = reader.read(path)
  |   File "/Users/tiao/.virtualenvs/blog/lib/python2.7/site-packages/pelican/readers.py", line 238, in read
  |     content = self._md.convert(text)
  |   File "/Users/tiao/.virtualenvs/blog/lib/python2.7/site-packages/markdown/__init__.py", line 368, in convert
  |     self.lines = prep.run(self.lines)
  |   File "/Users/tiao/Dropbox/Projects/website/plugins/liquid_tags/mdx_liquid_tags.py", line 44, in run
  |     liquid_tags[i] = self._tags[tag](self, tag, markup.strip())
  |   File "/Users/tiao/Dropbox/Projects/website/plugins/liquid_tags/notebook.py", line 298, in notebook
  |     (body, resources) = exporter.from_notebook_node(nb_json)
  |   File "/Users/tiao/.virtualenvs/blog/lib/python2.7/site-packages/IPython/nbconvert/exporters/html.py", line 57, in from_notebook_node
  |     return super(HTMLExporter, self).from_notebook_node(nb, resources, **kw)
  |   File "/Users/tiao/.virtualenvs/blog/lib/python2.7/site-packages/IPython/nbconvert/exporters/templateexporter.py", line 208, in from_notebook_node
  |     nb_copy, resources = super(TemplateExporter, self).from_notebook_node(nb, resources, **kw)
  |   File "/Users/tiao/.virtualenvs/blog/lib/python2.7/site-packages/IPython/nbconvert/exporters/exporter.py", line 125, in from_notebook_node
  |     nb_copy, resources = self._preprocess(nb_copy, resources)
  |   File "/Users/tiao/.virtualenvs/blog/lib/python2.7/site-packages/IPython/nbconvert/exporters/exporter.py", line 278, in _preprocess
  |     nbc, resc = preprocessor(nbc, resc)
  |   File "/Users/tiao/.virtualenvs/blog/lib/python2.7/site-packages/IPython/nbconvert/preprocessors/coalescestreams.py", line 28, in wrappedfunc
  |     for index, cell in enumerate(nb.cells):
  |   File "/Users/tiao/.virtualenvs/blog/lib/python2.7/site-packages/IPython/utils/ipstruct.py", line 149, in __getattr__
  |     raise AttributeError(key)
  | AttributeError: cells
```

### PR DESCRIPTION
**Pull request by benjaminabel**
This PR add support for the ipython 3.x notebooks in liquid_tags plugins. It fixes #427 and implements code proposed in #445, you can view the conversation about these commits in #445.

- use tox to run tests for ipython 2&3 on notebooks written in nbformat 3&4
- fix ipython 3 compatibility
- add a template for collapsable cells for ipython 3.

### CODE REVIEW

**Comment by FRidh** [comment]
@benjaminabel @justinmayer 
Sorry for the late update, I completely forgot about this.

I tried running tox but had some difficulties. I should say I am really not familiar with tox. Apparently tox 1.5.0 which is available in Anaconda doesn't work. 
```
tox.ConfigError: ConfigError: substitution key '27,34' not found
```
I installed latest via pip (1.9.2) and ran it from my base conda Python 3.4 installation. With that I got many InvocationErrors. I suppose this is just due to an incompatibility between conda and tox?

Nevertheless, all tests passed with nose in my current environment Python3.4 / IPython 3.1. I've also rebuilt my blog locally with this PR and it worked just fine. Collapsible cells I don't use and didn't test though.

**Comment by benjaminabel** [comment]
Thanks @FRidh I cited your work in the PR, however I didn't include your commit, sorry.

**Comment by benjaminabel** [comment]
@justinmayer I think it's finished, any thoughts? If some issues appears in the future, I'll try to fix them.

**Comment by Keats** [comment]
Looks good to me as well, would be nice to have this merged

**Comment by justinmayer** [comment]
Thanks to @benjaminabel and @fridh for the work on these enhancements.

**Comment by cranmer** [comment]
My travis based installation is working for me now IPython3. Thanks!

**Pull request merged**
