### PR TITLE
liquid_tag : replace div to span

### PR DESCRIPTION
**Pull request by mothsART**
Same problematic than #786

### CODE REVIEW

**Comment by justinmayer** [comment]
@jakevdp: Any comments on this pull request?

**Comment by jakevdp** [comment]
Sure, seems reasonable.

**Comment by justinmayer** [comment]
@mothsART: Would you please resolve conflicts / rebase on current master?

**Comment by mothsART** [comment]
sorry, a wrong git manip => resolve on #814

**Pull request closed without merging**
