### PR TITLE
Add plugin: replacer

### PR DESCRIPTION
**Pull request by narusemotoki**
This plugin replace a text of a generated HTML.

### CODE REVIEW

**Comment by justinmayer** [comment]
提出ありがとうございます。(^_^)

**Comment by narusemotoki** [comment]
Thank you! :bow: I like pelican. It's best blog tool to me!

**Comment by zackw** [comment]
This broke the repository!

    $ git submodule update --recursive --init
    fatal: reference is not a tree: 7ce49d52ebfa2b5be81bb1ea8a77b57d65d770d9
    Unable to checkout '7ce49d52ebfa2b5be81bb1ea8a77b57d65d770d9' in submodule path 'replacer'

@narusemotoki Did you rebase your plugin after this got merged, or something?  You mustn't do that.

**Comment by justinmayer** [comment]
I removed and re-added the Replacer plugin's submodule entry. Please let me know if this continues to pose a problem.

**Comment by narusemotoki** [comment]
@zackw I'm so sorry.
@justinmayer Thank you so match.

**Pull request merged**
