### PR TITLE
Updated html snippet of youtube

### PR DESCRIPTION
**Pull request by Azd325**
Updated the youtube url to get the embedded player to work again

### CODE REVIEW

**Comment by claman** [comment]
I tried making these changes, but they don't seem to work.

I'm using Safari 8.0.2 on OS X 10.10.1

**Comment by Azd325** [comment]
@claman Do you mean the relative urls?

**Comment by claman** [comment]
@Azd325 sorry, probably should have commented on the code itself; I mean the change from `src='http://www.youtube.com/v/{youtube_id}'` to `src='//www.youtube.com/embed/{youtube_id}'`

**Comment by Azd325** [comment]
@claman I don't have a safari. Can you check which embed code is shown on the youtube page if you click share. In chrome and firefox is the default with "//" only

**Comment by claman** [comment]
@Azd325 it's with "//" only

**Comment by justinmayer** [comment]
Thanks for the submission. As mentioned on Paul Irish's [treatise on protocol-relative URLs](http://www.paulirish.com/2010/the-protocol-relative-url/), this technique is now deemed an anti-pattern. I can't think of any reason not to use HTTPS for all YouTube links.

After making those changes, please squash your commits. Thanks!

**Comment by Azd325** [comment]
@justinmayer Changes are made. 

Maybe we should close than #393. If we don't want to use this anti-pattern in the liquid-tags.

**Comment by justinmayer** [comment]
Thanks, Tim!

**Pull request merged**
