### PR TITLE
Add Members plugin to list member info in metadata

### PR DESCRIPTION
**Pull request by daneoshiga**

### CODE REVIEW

**Comment by justinmayer** [comment]
Thanks for the contribution, Danilo. I made a few suggested wording changes. Does this plugin support Markdown as well?

**Comment by daneoshiga** [comment]
Ok, I'll change it, english isn't my primary language so thanks for the help.

I still have to test it with markdown, gonna do it and fix if needed.

**Comment by justinmayer** [comment]
Hi Danilo. Any updates?

**Comment by daneoshiga** [comment]
sorry justin, I was on Python Brasil these days, gonna touch this still this week

**Comment by justinmayer** [comment]
Thanks, Danilo. Any word on whether your plugin works with Markdown?

Also, when you're done making changes, would you please [rebase & squash your commits](https://github.com/getpelican/pelican/wiki/Git-Tips#squashing-commits)?

**Comment by justinmayer** [comment]
Hi Danilo. Any updates on this PR?

**Comment by daneoshiga** [comment]
Hi Justin, sorry for taking so long, now it is working with markdown too, commit rebased and squased too, hope it is ok.

**Comment by justinmayer** [comment]
No worries! Many thanks for the contribution, Danilo.

**Pull request merged**
