### PR TITLE
Fix issue #1022

### PR DESCRIPTION
**Pull request by Naereen**
(it should) fix issue #1022.

### CODE REVIEW

**Comment by Naereen** [comment]
Hi. Nobody can merge this? It looks OK.

**Comment by justinmayer** [comment]
@linevych, @mattvonrocketstein, @lindzey, and @johnmarkschofield: Would you mind taking a look at this PR and advising @Naereen with any comments you may have?

**Comment by Naereen** [comment]
Thanks @justinmayer.

**Comment by justinmayer** [comment]
Last call for comment on this PR. Any thoughts?

(@johnmarkschofield: Cheers from a fellow SFV native. I grew up a bit further west of Tarzana, just before the Calabasas grade.)

**Comment by justinmayer** [comment]
Please see: https://github.com/getpelican/pelican-plugins/issues/1022#issuecomment-754088915

**Pull request closed without merging**
