### PR TITLE
clone submodules too when installing

### PR DESCRIPTION
**Pull request by benjaminabel**

### CODE REVIEW

**Comment by kylef** [comment]
This PR also has a change you didn't mention, which is going from https checkout to SSH checkout which then requires the user to have a GitHub account and an SSH key attached.

Can you revert the second change so this can become merged?

**Comment by benjaminabel** [comment]
@kylef Sorry I didn't see that change, you're right, it's better to stay in https.

**Comment by kylef** [comment]
Thanks for updating @benjaminabel.

**Comment by benjaminabel** [comment]
You're welcome

**Pull request merged**
