### PR TITLE
Add the pelican_commonmark plugin

### PR DESCRIPTION
**Pull request by niligulmohar**
This provides a reader for markdown files that uses the Python parser
for CommonMark.

### CODE REVIEW

**Comment by kylef** [comment]
Looking at this implementation, I don't think this would actually work. You don't seem to register the newly created reader. Take a look at the documentation on creating a reader: http://docs.getpelican.com/en/latest/plugins.html#how-to-create-a-new-reader

It would probably also make sense to un-register the markdown reader too.

**Comment by niligulmohar** [comment]
I found it was only necessary to have a `file_extensions` property, and to subclass `BaseReader`. `Readers.__init__` then handles registering the reader.

But perhaps I shouldn't rely on this behavior?

**Comment by niligulmohar** [comment]
Suggested improvement:  69891dd

Now all extensions for the `MarkdownReader` are changed to the `CommonMarkReader` through the `readers_init` signal.

**Comment by avaris** [comment]
It's true that if you subclass `BaseReader`, you won't need to explicitly add the reader. But this relies on the order of `Reader` object instantiation and the import of your plugin. If import doesn't come first, it won't work. Currently, pelican will import plugins first, but it's not guaranteed that it'll be like this in the future.

**Comment by justinmayer** [comment]
Given the inactivity, I am closing this pull request for now.

@niligulmohar: If you would like to continue working on your CommonMark plugin, please post a comment here, and I will re-open.

**Pull request closed without merging**
