### PR TITLE
Added PlantUML extension for Markdown syntax

### PR DESCRIPTION
**Pull request by mikitex70**
Extended the plugin to support also the Markdown syntax.
In Markdown, UML blocks are delimited with ::uml:: and ::end-uml::
The RST plugin auto-registers also the Markdown extension, if Python-Markdown is present.

### CODE REVIEW

**Comment by stevepowell99** [comment]
thanks for all that - but now I am not sure how I am to install the plugin. If I clone the whole set

    git clone https://github.com/mikitex70/pelican-plugins.git

I now, on running pelican, get the error 

    ERROR: Can't find plugin `plantuml-markdown`: No module named plantuml-markdown

and indeed there is no such subfolder in the pelican-plugins folder. If do 

    cd pelican-plugins

    git clone https://github.com/mikitex70/plantuml-markdown.git

then I get the expected subfolder but the same error Can't find plugin `plantuml-markdown`

**Comment by stevepowell99** [comment]
oh, and  using 

    make DEBUG=1 html

I get 

    DEBUG: Temporarily adding PLUGIN_PATHS to system path
    DEBUG: Loading plugin `plantuml-markdown`
    ERROR: Can't find plugin `plantuml-markdown`: No module named plantuml-markdown

etc

**Comment by mikitex70** [comment]
Hi Steve, I've tried to clone my plugins from GitHub to my test machine as you have done, but all is working. Please check the name of the plugin in `pelicanconf.py`: the correct name is `plantuml` and not `plantuml-markdown` (`rst` and `md` posts are handled by the same plugin).

If you are unable to fine the problem, try to download my test blog from https://drive.google.com/open?id=0B4KBZI38p-PHRHRhOGh4ZXpxX2c&authuser=0, clone in it my plugins repository and try `make html`. If it works, give a look to the `pelicanconf.py`, maybe there something different from yours.

**Comment by stevepowell99** [comment]
thanks! I did what you suggested, ran

    make html

and got

    WARNING: Could not process ./2014-12-21-uml-md-test.md
    'format'
    Done: Processed 0 article(s), 0 draft(s) and 0 page(s) in 0.09 seconds.

This is because of missing format specification in some of the code blocks
(yes I know they are not supposed to be necessary.). If I supply format
specifications, I get


    pelican /media/steve/ssd/steve@promente.net/Projects/pelicanbook/content
-o /media/steve/ssd/steve@promente.net/Projects/pelicanbook/output -s
/media/steve/ssd/steve@promente.net/Projects/pelicanbook/pelicanconf.py
    WARNING: Could not process ./2014-12-21-uml-md-test.md
    [Errno 2] No such file or directory
    Done: Processed 59 article(s), 0 draft(s) and 0 page(s) in 1.32 seconds.

So I guess it must be something to do with my plantuml installation, but
like I say, plantuml is installed and in the path and working. I wonder if
python is using a different path from my system?




________________________________________________
www.promente.org
skype: stevepowell99
mobile: +387 61 215 997

**Comment by stevepowell99** [comment]
Now I started from scratch and installed everything as per your suggestion

    $ sudo apt-get install graphviz
    $ sudo mkdir -p /opt/plantuml
    $ sudo wget 'http://sourceforge.net/projects/plantuml/files/plantuml.jar/download' -O /opt/plantuml/plantuml.jar
    $ sudo apt-get install default-jdk
    $ cat <<EOF >> /tmp/plantuml
    #!/bin/bash
    java -jar /opt/plantuml/plantuml.jar $\{@}
    EOF
    $ chmod +x /tmp/plantuml
    $ sudo cp /tmp/plantuml /usr/bin/

And then tried to compile your test site, but I still get the same error.

    Could not process ./2014-12-21-uml-md-test.md
    [Errno 2] No such file or directory

**Comment by mikitex70** [comment]
Hi Steve,
I've created a clean user, reinstalled pelican as in your steps and I was able to reproduce the problem.
To correct it, edit your `/usr/bin/plantuml`  and change the line

    java -jar /opt/plantuml/plantuml.jar $\{@}

in

    java -jar /opt/plantuml/plantuml.jar ${@}

and try again. This resolve the problem, at least in my test user.
The backslash is an error: catting from command line builds a wrong bash script.

**Comment by stevepowell99** [comment]
thanks well ...
I still get asked for format and classes, not sure what to put for classes.

I tried this

Title: plant
Date:


::uml:: format="png" classes="sequence" alt="Sample sequence diagram"
participant User

  [First component]
  [Another component] as Comp2
  component Comp3
  component [Last\ncomponent] as Comp4

::end-uml::

and get

WARNING: Could not process About/plantuml.md
Error calling plantuml: Error line 3 in file: /tmp/tmpQiV4T1
Some diagram description contains errors

If I leave out the classes parameter, I get

WARNING: Could not process About/plantuml.md
'classes'




________________________________________________
www.promente.org
skype: stevepowell99
mobile: +387 61 215 997

**Comment by mikitex70** [comment]
You are mixing sequence diagrams and component diagrams: test your UML with the applet in http://plantuml.sourceforge.net. If you comment the `participant User` (put a single quote before it) the UML will be converted into png image.
In case of errors, give a look into the generated temporary file (`/tmp/tmpQiV4T1` in your example): it contains the PlantUML code so you can try to identify the problems, for example pasting it in the applet on the PlantUML site or converting from command line.

**Comment by stevepowell99** [comment]
wow, I had the line

DESCRIPTION = u'Rethinking M&E'

in my config and somehow the & was causing the images to be sourced from
the h/ folder??

I also got errors with

MD_EXTENSIONS =  [ 'toc', 'codehilite','extra']

not sure which one of these three was the problem. So took these out (don't
really need them) and the plug-in is working fine so far.

Unfortunately your plug-in is also incompatible with the pandoc_reader
plugin which I really need for providing references in my articles. If I
set

PLUGINS = ['plantuml','pandoc_reader']

then the UML is not processed at all.

would be great if there was a workaround for the pandoc_reader plugin
because I need that just as much as I need plantuml!







________________________________________________
www.promente.org
skype: stevepowell99
mobile: +387 61 215 997

**Comment by mikitex70** [comment]
Hi Steve, I've studied your problem and it's not easy to resolve: pandoc uses his own parser so any pelican plugin is ignored.
But ... I've found a script that I've adapted so you can generate PlantUML diagrams from pandoc.
If you do a pull of my repository you will find a new file, `pandoc-plantuml`. Read the Readme.rst or the `pandoc-plantuml` header for instructions on installation and usage.
In the meantime I will test the `plantuml` plugin with others (`toc`, `codehilite`, `extra`).

**Comment by stevepowell99** [comment]
wow that was quick! Thanks again.
I tried your new method but without success so far.

Putting pandoc-plantuml in the root of the pelican blog, I got the error

pandoc: Filter pandoc-plantuml not found

Putting it in the content folder, I got the error

pandoc: Error running filter pandoc-plantuml
fd:3: hClose: resource vanished (Broken pipe)







________________________________________________
www.promente.org
skype: stevepowell99
mobile: +387 61 215 997

**Comment by stevepowell99** [comment]
the plantuml plugin seems to break normal markdown footnotes ^[footnotes]
too?
By the way, after giving up on the new method, I had to reinstall the
previous version of plantuml plugin. With today's newer version, I couldn't
get the old configuration (with PLUGINS = ['plantuml']) to work.



________________________________________________
www.promente.org
skype: stevepowell99
mobile: +387 61 215 997

**Comment by mikitex70** [comment]
Move the `pandoc-plantuml` file in a subfolder and update the  `PANDOC_ARGS` configuration.
It seems that pandoc requires extensions in a subfolder...
If you use the `pandoc_reader` the `plantuml` pelican plugin is ignored, keep it out from your configuration.
Also, keep in mind the difference in syntax: with `plantuml` plugin you must write

    ::uml::
    ::end-uml::

while with the `pandoc-plantuml` filter the syntax become:

    ```plantuml
    @startuml
    @enduml
    ```

**Comment by mikitex70** [comment]
I've forgotten on thing: do another pull of my repository, I've corrected a stupid error in the `pandoc-plantuml` file.

**Comment by stevepowell99** [comment]
Right, I did all that but no luck. The citations are not converted by
pandoc_reader and the graphs remain as code blocks. The debug message said
to empty the cache, so I did that, and then I got this:

 make DEBUG=1 html
pelican /media/steve/ssd/steve@promente.net/Projects/pelicanbook/content -o
/media/steve/ssd/steve@promente.net/Projects/pelicanbook/output -s
/media/steve/ssd/steve@promente.net/Projects/pelicanbook/pelicanconf.py  -D
DEBUG: Adding current directory to system path
DEBUG: Temporarily adding PLUGIN_PATHS to system path
DEBUG: Loading plugin `pandoc_reader`
DEBUG: Registering plugin `pandoc_reader`
DEBUG: Restoring system path
DEBUG: template list: [u'!simple/archives.html', u'!simple/article.html',
u'!simple/author.html', u'!simple/authors.html', u'!simple/base.html',
u'!simple/categories.html', u'!simple/category.html',
u'!simple/gosquared.html', u'!simple/index.html', u'!simple/page.html',
u'!simple/pagination.html', u'!simple/period_archives.html',
u'!simple/tag.html', u'!simple/tags.html', u'!simple/translations.html',
u'analytics.html', u'archives.html', u'article.html', u'author.html',
u'authors.html', u'base.html', u'categories.html', u'category.html',
u'comments.html', u'disqus_script.html', u'github.html', u'gosquared.html',
u'index.html', u'page.html', u'pagination.html', u'period_archives.html',
u'piwik.html', u'tag.html', u'taglist.html', u'tags.html',
u'translations.html', u'twitter.html']
DEBUG: read file images/image007.jpg -> Static
DEBUG: signal <blinker.base.NamedSignal object at 0x2ace5f1f7150;
u'static_generator_preread'>.send(<pelican.generators.StaticGenerator
object at 0x2ace62719d90>)
DEBUG: signal <blinker.base.NamedSignal object at 0x2ace5f1f7190;
u'static_generator_context'>.send(<pelican.generators.StaticGenerator
object at 0x2ace62719d90>, <metadata>)
DEBUG: read file images/image012.png -> Static
DEBUG: read file images/image005.png -> Static
DEBUG: read file images/image004.png -> Static
DEBUG: read file images/image001.png -> Static
DEBUG: read file images/image002.png -> Static
DEBUG: read file images/image014.png -> Static
DEBUG: read file images/image013.png -> Static
DEBUG: read file images/image017.png -> Static
DEBUG: read file images/image020.jpg -> Static
DEBUG: read file images/image009.png -> Static
DEBUG: read file images/image011.png -> Static
DEBUG: read file images/image008.jpg -> Static
DEBUG: read file images/image003.png -> Static
DEBUG: read file images/image016.png -> Static
DEBUG: read file images/image021.png -> Static
DEBUG: read file images/image015.jpg -> Static
DEBUG: read file images/image018.png -> Static
DEBUG: read file images/image006.png -> Static
DEBUG: read file images/image010.png -> Static
DEBUG: read file images/image019.jpg -> Static
DEBUG: read file Controversial theses/RCTs.md -> Article
DEBUG: signal <blinker.base.NamedSignal object at 0x2ace5f1f7050;
u'article_generator_preread'>.send(<pelican.generators.ArticlesGenerator
object at 0x2ace62722350>)
DEBUG: signal <blinker.base.NamedSignal object at 0x2ace5f1f7090;
u'article_generator_context'>.send(<pelican.generators.ArticlesGenerator
object at 0x2ace62722350>, <metadata>)
DEBUG: read file Controversial theses/HigherIsBroken.md -> Article
DEBUG: read file Controversial theses/template-disagreements.md -> Article
DEBUG: read file Controversial theses/tufte.md -> Article
DEBUG: read file Controversial theses/strength.md -> Article
DEBUG: read file Controversial theses/EffectivenessIsBroken.md -> Article
DEBUG: read file Tricky cases/paradox-of-evaluation-counterfactuals.md ->
Article
DEBUG: read file Tricky cases/contribution.md -> Article
DEBUG: read file Tricky cases/fire-service.md -> Article
DEBUG: read file About/plantuml.md -> Article
DEBUG: read file About/plantuml.md -> Draft
DEBUG: read file About/about.md -> Article
pandoc: Filter pandoc_extensions/pandoc-plantuml not found
DEBUG: read file About/plantuml2.md -> Article
DEBUG: read file About/plantuml2.md -> Draft
DEBUG: read file Chapter 1 - Logic Models, Planning and Monitoring/
general-and-specific.md -> Article
DEBUG: read file Chapter 1 - Logic Models, Planning and Monitoring/
ghost-results.md -> Article
DEBUG: read file Chapter 1 - Logic Models, Planning and Monitoring/
restrictions.md -> Article
DEBUG: read file Chapter 1 - Logic Models, Planning and Monitoring/
extension-timelines.md -> Article
DEBUG: read file Chapter 1 - Logic Models, Planning and Monitoring/
assumptions-and-context.md -> Article
DEBUG: read file Chapter 1 - Logic Models, Planning and Monitoring/
about-chapter-1.md -> Article
DEBUG: read file Chapter 1 - Logic Models, Planning and Monitoring/
theory-model-all.md -> Article
DEBUG: read file Chapter 4 - Comparison with alternative approaches/
alternatives-to-functions.md -> Article
DEBUG: read file Chapter 3 - Practical steps/vision.md -> Article
DEBUG: read file Chapter 2 - Evaluation and Learning/relevance.md -> Article
DEBUG: read file Chapter 2 - Evaluation and Learning/about-chapter-2.md ->
Article
DEBUG: read file Chapter 2 - Evaluation and Learning/difference.md ->
Article
DEBUG: read file Chapter 2 - Evaluation and Learning/impact.md -> Article
DEBUG: read file Chapter 2 - Evaluation and Learning/
key-evaluation-questions.md -> Article
DEBUG: read file Chapter 2 - Evaluation and Learning/partial-attribution.md
-> Article
DEBUG: read file Chapter 2 - Evaluation and Learning/impact-total.md ->
Article
DEBUG: read file Chapter 2 - Evaluation and Learning/ambition.md -> Article
DEBUG: read file Chapter 2 - Evaluation and Learning/anecdotes.md -> Article
DEBUG: read file Chapter 2 - Evaluation and Learning/method.md -> Article
DEBUG: read file Chapter 2 - Evaluation and Learning/
impact-outcome-and-inus-causes.md -> Article
DEBUG: read file Chapter 2 - Evaluation and Learning/map.md -> Article
DEBUG: read file Chapter 2 - Evaluation and Learning/target-achievement.md
-> Article
DEBUG: read file Chapter 2 - Evaluation and Learning/not-just-plans.md ->
Article
DEBUG: read file Chapter 2 - Evaluation and Learning/evaluator.md -> Article
DEBUG: read file Philosophy/reductionism.md -> Article
DEBUG: read file Philosophy/causation.md -> Article
DEBUG: read file Philosophy/what-counts-as-evidence.md -> Article
DEBUG: read file Philosophy/intention.md -> Article
DEBUG: read file Chapter 0 - A formal theory of logic models/
05-counterfactuals-and-differences.md -> Article
DEBUG: read file Chapter 0 - A formal theory of logic models/intentional.md
-> Article
DEBUG: read file Chapter 0 - A formal theory of logic models/
06-estimating.md -> Article
DEBUG: read file Chapter 0 - A formal theory of logic models/03-joining.md
-> Article
DEBUG: read file Chapter 0 - A formal theory of logic models/
20-evaluation.md -> Article
DEBUG: read file Chapter 0 - A formal theory of logic models/
04-intervention.md -> Article
DEBUG: read file Chapter 0 - A formal theory of logic models/monitoring.md
-> Article
DEBUG: read file Chapter 0 - A formal theory of logic models/
08-summarizers.md -> Article
DEBUG: read file Chapter 0 - A formal theory of logic models/indicator.md
-> Article
DEBUG: read file Chapter 0 - A formal theory of logic models/
08.2-summarizers-data.md -> Article
DEBUG: read file Chapter 0 - A formal theory of logic models/01-variable.md
-> Article
DEBUG: read file Chapter 0 - A formal theory of logic
models/07-getting-to-LMs.md -> Article
DEBUG: read file Chapter 0 - A formal theory of logic models/09-target.md
-> Article
DEBUG: read file Chapter 0 - A formal theory of logic models/
08.1-summarizers-story.md -> Article
DEBUG: read file Chapter 0 - A formal theory of logic models/
00-about-chapter-0.md -> Article
DEBUG: read file Chapter 0 - A formal theory of logic models/
variables-fuzzy-and-formal.md -> Article
DEBUG: read file Chapter 0 - A formal theory of logic models/02-theory.md
-> Article
DEBUG: read file Chapter 0 - A formal theory of logic models/
tricky-variables.md -> Article
DEBUG: read file Chapter 0 - A formal theory of logic models/M&E.md ->
Article
DEBUG: read file The Blog/linus-on-having-a-vision-or-not.md -> Article
DEBUG: read file The Blog/
progress-markers-boundary-partners-and-item-response-theory.md -> Article
DEBUG: read file The Blog/
the-five-year-plan-is-dead-long-live-the-five-year-plan.md -> Article
-> copying /media/steve/ssd/
steve@promente.net/Projects/pelicanbook/content/images/image007.jpg to
images/image007.jpg
-> copying /media/steve/ssd/
steve@promente.net/Projects/pelicanbook/content/images/image012.png to
images/image012.png
-> copying /media/steve/ssd/
steve@promente.net/Projects/pelicanbook/content/images/image005.png to
images/image005.png
-> copying /media/steve/ssd/
steve@promente.net/Projects/pelicanbook/content/images/image004.png to
images/image004.png
-> copying /media/steve/ssd/
steve@promente.net/Projects/pelicanbook/content/images/image001.png to
images/image001.png
-> copying /media/steve/ssd/
steve@promente.net/Projects/pelicanbook/content/images/image002.png to
images/image002.png
-> copying /media/steve/ssd/
steve@promente.net/Projects/pelicanbook/content/images/image014.png to
images/image014.png
-> copying /media/steve/ssd/
steve@promente.net/Projects/pelicanbook/content/images/image013.png to
images/image013.png
-> copying /media/steve/ssd/
steve@promente.net/Projects/pelicanbook/content/images/image017.png to
images/image017.png
-> copying /media/steve/ssd/
steve@promente.net/Projects/pelicanbook/content/images/image020.jpg to
images/image020.jpg
-> copying /media/steve/ssd/
steve@promente.net/Projects/pelicanbook/content/images/image009.png to
images/image009.png
-> copying /media/steve/ssd/
steve@promente.net/Projects/pelicanbook/content/images/image011.png to
images/image011.png
-> copying /media/steve/ssd/
steve@promente.net/Projects/pelicanbook/content/images/image008.jpg to
images/image008.jpg
-> copying /media/steve/ssd/
steve@promente.net/Projects/pelicanbook/content/images/image003.png to
images/image003.png
-> copying /media/steve/ssd/
steve@promente.net/Projects/pelicanbook/content/images/image016.png to
images/image016.png
-> copying /media/steve/ssd/
steve@promente.net/Projects/pelicanbook/content/images/image021.png to
images/image021.png
-> copying /media/steve/ssd/
steve@promente.net/Projects/pelicanbook/content/images/image015.jpg to
images/image015.jpg
-> copying /media/steve/ssd/
steve@promente.net/Projects/pelicanbook/content/images/image018.png to
images/image018.png
-> copying /media/steve/ssd/
steve@promente.net/Projects/pelicanbook/content/images/image006.png to
images/image006.png
-> copying /media/steve/ssd/
steve@promente.net/Projects/pelicanbook/content/images/image010.png to
images/image010.png
-> copying /media/steve/ssd/
steve@promente.net/Projects/pelicanbook/content/images/image019.jpg to
images/image019.jpg
-> writing /media/steve/ssd/
steve@promente.net/Projects/pelicanbook/output/feeds/steve.atom.xml
-> writing /media/steve/ssd/
steve@promente.net/Projects/pelicanbook/output/feeds/steve.rss.xml
-> writing /media/steve/ssd/
steve@promente.net/Projects/pelicanbook/output/feeds/steve-powell.atom.xml
-> writing /media/steve/ssd/
steve@promente.net/Projects/pelicanbook/output/feeds/steve-powell.rss.xml
-> writing /media/steve/ssd/
steve@promente.net/Projects/pelicanbook/output/00-about-chapter-0.html
-> writing /media/steve/ssd/
steve@promente.net/Projects/pelicanbook/output/1-variables.html
-> writing /media/steve/ssd/
steve@promente.net/Projects/pelicanbook/output/2-theories-intentional-processes.html
-> writing /media/steve/ssd/
steve@promente.net/Projects/pelicanbook/output/3-the-joining-rule.html
-> writing /media/steve/ssd/
steve@promente.net/Projects/pelicanbook/output/4-interventions.html
-> writing /media/steve/ssd/
steve@promente.net/Projects/pelicanbook/output/5-counterfactuals-and-differences.html
-> writing /media/steve/ssd/
steve@promente.net/Projects/pelicanbook/output/6-estimating-the-counterfactual-what-would-have-happened-if.html
-> writing /media/steve/ssd/
steve@promente.net/Projects/pelicanbook/output/7-getting-to-lms.html
-> writing /media/steve/ssd/
steve@promente.net/Projects/pelicanbook/output/8-summarizers.html
-> writing /media/steve/ssd/
steve@promente.net/Projects/pelicanbook/output/about-chapter-1.html
-> writing /media/steve/ssd/
steve@promente.net/Projects/pelicanbook/output/about-chapter-2.html
-> writing /media/steve/ssd/
steve@promente.net/Projects/pelicanbook/output/about-this-book.html
-> writing /media/steve/ssd/
steve@promente.net/Projects/pelicanbook/output/an-arrow-says-nothing-about-the-strength-of-the-influence.html
-> writing /media/steve/ssd/
steve@promente.net/Projects/pelicanbook/output/anecdotes.html
-> writing /media/steve/ssd/
steve@promente.net/Projects/pelicanbook/output/calling-levels-of-a-logic-model-high-or-low-doesnt-work.html
-> writing /media/steve/ssd/
steve@promente.net/Projects/pelicanbook/output/causation.html
-> writing /media/steve/ssd/
steve@promente.net/Projects/pelicanbook/output/contribution.html
-> writing /media/steve/ssd/
steve@promente.net/Projects/pelicanbook/output/differences.html
-> writing /media/steve/ssd/
steve@promente.net/Projects/pelicanbook/output/disagreement-with-standard-logic-model-templates.html
-> writing /media/steve/ssd/
steve@promente.net/Projects/pelicanbook/output/effectiveness-is-broken.html
-> writing /media/steve/ssd/
steve@promente.net/Projects/pelicanbook/output/evaluation.html
-> writing /media/steve/ssd/
steve@promente.net/Projects/pelicanbook/output/evaluation-maps.html
-> writing /media/steve/ssd/
steve@promente.net/Projects/pelicanbook/output/extension-timelines.html
-> writing /media/steve/ssd/
steve@promente.net/Projects/pelicanbook/output/general-and-specific-variables-and-theories.html
-> writing /media/steve/ssd/
steve@promente.net/Projects/pelicanbook/output/ghost-results.html
-> writing /media/steve/ssd/
steve@promente.net/Projects/pelicanbook/output/impact.html
-> writing /media/steve/ssd/
steve@promente.net/Projects/pelicanbook/output/impact-total-impact.html
-> writing /media/steve/ssd/
steve@promente.net/Projects/pelicanbook/output/indicators.html
-> writing /media/steve/ssd/
steve@promente.net/Projects/pelicanbook/output/intention.html
-> writing /media/steve/ssd/
steve@promente.net/Projects/pelicanbook/output/intentional-processes-projects-and-programmes.html
-> writing /media/steve/ssd/
steve@promente.net/Projects/pelicanbook/output/key-evaluation-questions.html
-> writing /media/steve/ssd/
steve@promente.net/Projects/pelicanbook/output/late-variables-and-process-variables.html
-> writing /media/steve/ssd/
steve@promente.net/Projects/pelicanbook/output/me.html
-> writing /media/steve/ssd/
steve@promente.net/Projects/pelicanbook/output/method.html
-> writing /media/steve/ssd/
steve@promente.net/Projects/pelicanbook/output/monitoring.html
-> writing /media/steve/ssd/
steve@promente.net/Projects/pelicanbook/output/not-just-plans.html
-> writing /media/steve/ssd/
steve@promente.net/Projects/pelicanbook/output/other-ways-to-express-theories-rather-than-as-functions.html
-> writing /media/steve/ssd/
steve@promente.net/Projects/pelicanbook/output/partial-attribution.html
-> writing /media/steve/ssd/
steve@promente.net/Projects/pelicanbook/output/rcts.html
-> writing /media/steve/ssd/
steve@promente.net/Projects/pelicanbook/output/relevance.html
-> writing /media/steve/ssd/
steve@promente.net/Projects/pelicanbook/output/summarizers-data-summarizers.html
-> writing /media/steve/ssd/
steve@promente.net/Projects/pelicanbook/output/summarizers-story-summarizers.html
-> writing /media/steve/ssd/
steve@promente.net/Projects/pelicanbook/output/target-achievement.html
-> writing /media/steve/ssd/
steve@promente.net/Projects/pelicanbook/output/target-ambition.html
-> writing /media/steve/ssd/
steve@promente.net/Projects/pelicanbook/output/targets.html
-> writing /media/steve/ssd/
steve@promente.net/Projects/pelicanbook/output/the-fire-service.html
-> writing /media/steve/ssd/
steve@promente.net/Projects/pelicanbook/output/the-job-of-the-evaluator.html
-> writing /media/steve/ssd/
steve@promente.net/Projects/pelicanbook/output/theories-models-intentional-processes.html
-> writing /media/steve/ssd/
steve@promente.net/Projects/pelicanbook/output/tufte-and-infographic-extremism.html
-> writing /media/steve/ssd/
steve@promente.net/Projects/pelicanbook/output/unnecessary-restrictions-in-logic-models.html
-> writing /media/steve/ssd/
steve@promente.net/Projects/pelicanbook/output/variables-fuzzy-and-formal.html
-> writing /media/steve/ssd/
steve@promente.net/Projects/pelicanbook/output/vision.html
-> writing /media/steve/ssd/
steve@promente.net/Projects/pelicanbook/output/what-counts-as-evidence.html
-> writing /media/steve/ssd/
steve@promente.net/Projects/pelicanbook/output/assumptions-and-context-in-logic-models.html
-> writing /media/steve/ssd/
steve@promente.net/Projects/pelicanbook/output/the-five-year-plan-is-dead-long-live-the-five-year-plan.html
-> writing /media/steve/ssd/
steve@promente.net/Projects/pelicanbook/output/impact-outcome-and-inus-causes.html
-> writing /media/steve/ssd/
steve@promente.net/Projects/pelicanbook/output/progress-markers-boundary-partners-and-item-response-theory.html
-> writing /media/steve/ssd/
steve@promente.net/Projects/pelicanbook/output/linus-on-having-a-vision-or-not.html
-> writing /media/steve/ssd/
steve@promente.net/Projects/pelicanbook/output/paradox-of-evaluation-counterfactuals.html
-> writing /media/steve/ssd/
steve@promente.net/Projects/pelicanbook/output/reductionism.html
-> writing /media/steve/ssd/
steve@promente.net/Projects/pelicanbook/output/index.html
-> writing /media/steve/ssd/
steve@promente.net/Projects/pelicanbook/output/index2.html
-> writing /media/steve/ssd/
steve@promente.net/Projects/pelicanbook/output/index3.html
-> writing /media/steve/ssd/
steve@promente.net/Projects/pelicanbook/output/index4.html
-> writing /media/steve/ssd/
steve@promente.net/Projects/pelicanbook/output/index5.html
-> writing /media/steve/ssd/
steve@promente.net/Projects/pelicanbook/output/tags.html
-> writing /media/steve/ssd/
steve@promente.net/Projects/pelicanbook/output/categories.html
-> writing /media/steve/ssd/
steve@promente.net/Projects/pelicanbook/output/authors.html
-> writing /media/steve/ssd/
steve@promente.net/Projects/pelicanbook/output/archives.html
-> writing /media/steve/ssd/
steve@promente.net/Projects/pelicanbook/output/tag/.html
-> writing /media/steve/ssd/
steve@promente.net/Projects/pelicanbook/output/tag/development.html
-> writing /media/steve/ssd/
steve@promente.net/Projects/pelicanbook/output/tag/baseline.html
-> writing /media/steve/ssd/
steve@promente.net/Projects/pelicanbook/output/tag/evaluation.html
-> writing /media/steve/ssd/
steve@promente.net/Projects/pelicanbook/output/tag/variables.html
-> writing /media/steve/ssd/
steve@promente.net/Projects/pelicanbook/output/tag/reproducibleresearch.html
-> writing /media/steve/ssd/
steve@promente.net/Projects/pelicanbook/output/tag/reductionism.html
-> writing /media/steve/ssd/
steve@promente.net/Projects/pelicanbook/output/tag/philosophical-headaches.html
-> writing /media/steve/ssd/
steve@promente.net/Projects/pelicanbook/output/tag/learning.html
-> writing /media/steve/ssd/
steve@promente.net/Projects/pelicanbook/output/tag/research.html
-> writing /media/steve/ssd/
steve@promente.net/Projects/pelicanbook/output/tag/cause.html
-> writing /media/steve/ssd/
steve@promente.net/Projects/pelicanbook/output/category/about.html
-> writing /media/steve/ssd/
steve@promente.net/Projects/pelicanbook/output/category/chapter-0-a-formal-theory-of-logic-models.html
-> writing /media/steve/ssd/
steve@promente.net/Projects/pelicanbook/output/category/chapter-0-a-formal-theory-of-logic-models2.html
-> writing /media/steve/ssd/
steve@promente.net/Projects/pelicanbook/output/category/chapter-1-logic-models-planning-and-monitoring.html
-> writing /media/steve/ssd/
steve@promente.net/Projects/pelicanbook/output/category/chapter-2-evaluation-and-learning.html
-> writing /media/steve/ssd/
steve@promente.net/Projects/pelicanbook/output/category/chapter-2-evaluation-and-learning2.html
-> writing /media/steve/ssd/
steve@promente.net/Projects/pelicanbook/output/category/chapter-3-practical-steps.html
-> writing /media/steve/ssd/
steve@promente.net/Projects/pelicanbook/output/category/chapter-4-comparison-with-alternative-approaches.html
-> writing /media/steve/ssd/
steve@promente.net/Projects/pelicanbook/output/category/controversial-theses.html
-> writing /media/steve/ssd/
steve@promente.net/Projects/pelicanbook/output/category/philosophy.html
-> writing /media/steve/ssd/
steve@promente.net/Projects/pelicanbook/output/category/the-blog.html
-> writing /media/steve/ssd/
steve@promente.net/Projects/pelicanbook/output/category/tricky-cases.html
-> writing /media/steve/ssd/
steve@promente.net/Projects/pelicanbook/output/author/steve.html
-> writing /media/steve/ssd/
steve@promente.net/Projects/pelicanbook/output/author/steve-powell.html
-> writing /media/steve/ssd/
steve@promente.net/Projects/pelicanbook/output/author/steve-powell2.html
-> writing /media/steve/ssd/
steve@promente.net/Projects/pelicanbook/output/author/steve-powell3.html
-> writing /media/steve/ssd/
steve@promente.net/Projects/pelicanbook/output/author/steve-powell4.html
-> writing /media/steve/ssd/
steve@promente.net/Projects/pelicanbook/output/author/steve-powell5.html
-> writing /media/steve/ssd/
steve@promente.net/Projects/pelicanbook/output/drafts/plant.html
-> writing /media/steve/ssd/
steve@promente.net/Projects/pelicanbook/output/drafts/plant2.html


The articles were not generated at all, I just have the navigation,
sidebar, and title, whether or not there is a plantuml graph or not. And
yes, I used the new syntax for the code blocks.


Then I just ran `pelican`, and got a message

pandoc: Filter pandoc_extensions/pandoc-plantuml not found

so I moved the subfolder to inside the content folder and ran pelican
again, and now I don't get that error. When I run make debug I get a
similar message to above, no errors. But still no article content.



________________________________________________
www.promente.org
skype: stevepowell99
mobile: +387 61 215 997

**Comment by justinmayer** [comment]
@stevepowell99: Instead of pasting error output directly, please use your preferred pastebin and include a link to it in your issue/comment. Doing so will keep the discussion readable and free of clutter. I've taken the liberty of editing your comment as an example for future reference.

@mikitex70: Many thanks for your work on this. Looking forward to merging once the dust has settled.  (^_^)

**Comment by mikitex70** [comment]
Hi Steve, I'm back.
I've tried to reproduce your problems but for me all it's working fine. The `pandoc-plantuml not found` from `pandoc` program is quite clear, the plugin is not found. Try to specify the full path in the `PANDOC_ARGS` variable of `pelicancon.py` and make sure the plugin is executable.
I've also tried citations and footnotes with pandoc and they are working fine.
The directive `MD_EXTENSIONS = [ 'toc', 'codehilite','extra'] ` you mentioned some post ago is useless (I think, maybe I'm wrong) because they are used by the `Python-Markdown` parser, and not by the `pandoc` parser that is used in your configuration.
If you still have troubles try to give me your settings for `PLUGINS`, `PANDOC_ARGS` and `PANDOC_EXTENSIONS`, and a little example of non-working `.md` article with citations, footnotes, code and everithing not working and I will try to help you.

**Comment by stevepowell99** [comment]
thanks. I just did a pelican-quickstart to make a new project, cloned your repository, then had to also clone pandoc_reader because it doesn't seem to be in your repository.

My config is standard http://pastebin.com/u47pAc9e
and my markdown is like this:

    Title: asdf
    Date:
    
    ```plantuml
    @startuml
      Alice -> Bob: Authentication Request
      Bob --> Alice: Authentication Response
    
      Alice -> Bob: Another authentication Request
      Alice <-- Bob: another authentication Response
    @enduml
    ```
    
But the codeblock is returned as-is, and there are no error messages of any kind either with make debug or just pelican.

**Comment by mandaris** [comment]
I want this to work. How can I help so that we get this ported to the main branch?

**Comment by mikitex70** [comment]
I have been busy at work in the last few months, but give me some day and I will check sources, push some patch that (I think) I've locally, do a merge with the main repository e make a pull request.

**Comment by mikitex70** [comment]
Plugin extended for Markdown syntax plus some fixes for Python 3.4.
Now ready for merging.

**Comment by tooh** [comment]
+1

**Comment by mikitex70** [comment]
Closing this pull request as is too old and seems forgotten.
I will open a new pull request.

**Comment by justinmayer** [comment]
Certainly not forgotten. It needed some commit squashing. Looking forward to the new pull request, which hopefully will be cleaner.  (^_^)

**Comment by justinmayer** [comment]
For posterity, this PR was replaced by the now-merged #775.

**Pull request closed without merging**
