### PR TITLE
Update plugin pelican-linkclass

### PR DESCRIPTION
**Pull request by rlaboiss**
The linkclass plugin was brokwn dute to changes in the Python Markdown module. This has been reported in https://github.com/rlaboiss/pelican-linkclass/issues/2 and fixed in commit https://github.com/rlaboiss/pelican-linkclass/commit/94dacf488a474c200a358a3e8e16a15e3cf34dfe.

Please update the pelican-linkclass submodule as per this pull request.

### CODE REVIEW

**Comment by Lucas-C** [comment]
Thanks for the fix !

I see that `pelican-linkclass` has unit tests, that's great !
I'd like to have them running in Travis CI before merging this. So either we wait for https://github.com/getpelican/pelican-plugins/issues/1170 or Travis CI is enabled on [](https://github.com/rlaboiss/pelican-linkclass), showing that they pass.
What do you think @rlaboiss ?

**Comment by rlaboiss** [comment]
I have no experience with Travis CI. Is there a short tutorial/guidelines on it? Otherwise, could you indicate to me the necessary steps for enabling Travis CI for my project?

**Comment by Lucas-C** [comment]
Sure @rlaboiss. This should be a quick 2-steps process:
- add a `.travis.yml` file to your repo with this content:
```
language: python
python:
    - "3.7"
cache: pip
install:
    # Installing pelican in editable mode makes its tests.support package available to us
    - pip install -e git+https://github.com/getpelican/pelican.git#egg=pelican
script: nosetests
```
- enable Travis CI for your repo on https://travis-ci.org/rlaboiss/pelican-linkclass

**Comment by rlaboiss** [comment]
Thanks, I did what you proposed. Could you please check if it works?

**Comment by Lucas-C** [comment]
Have you enabled this repo on https://travis-ci.org/account/repositories ?

Once you've done it, this PR will display Travis CI status on top of your README: https://github.com/rlaboiss/pelican-linkclass/pull/4

**Comment by rlaboiss** [comment]
> Have you enabled this repo on https://travis-ci.org/account/repositories ?

Yes: https://travis-ci.org/rlaboiss/pelican-linkclass
 
> Once you've done it, this PR will display Travis CI status on top of your README: [rlaboiss/pelican-linkclass#4](https://github.com/rlaboiss/pelican-linkclass/pull/4)

Thanks!

**Comment by Lucas-C** [comment]
Ok perfect. Now your repo status is "build: unknown" because it has never been executed yet.
You can either trigger a build manually on https://travis-ci.org/rlaboiss/pelican-linkclass (on the top-right drop-down menu), or push a new commit on the repo and Travis Ci should automatically launch a build job.

**Comment by rlaboiss** [comment]
I triggered manually the build But it used Ruby as language, instead of Python!
https://travis-ci.org/rlaboiss/pelican-linkclass/builds/583024904

**Comment by Lucas-C** [comment]
Ok strange.
Maybe try to commit a minor change to your README. Even just a newline should suffice.

**Comment by Lucas-C** [comment]
Here is a solution for a fix: https://github.com/rlaboiss/pelican-linkclass/pull/5

**Comment by rlaboiss** [comment]
> Here is a solution for a fix: [rlaboiss/pelican-linkclass#5](https://github.com/rlaboiss/pelican-linkclass/pull/5)

Great, thanks!

**Comment by Lucas-C** [comment]
The tests pass so if you update the pelican-linkclass submodule again in this PR, I'll merge it

**Comment by rlaboiss** [comment]
Done!

**Comment by rlaboiss** [comment]
I am lost here. Which are the conflicts? Where can I see them?

**Comment by avaris** [comment]
Can you also [squash](https://github.com/getpelican/pelican/wiki/Git-Tips#squashing-commits) the commits?

**Comment by rlaboiss** [comment]
> Can you also [squash](https://github.com/getpelican/pelican/wiki/Git-Tips#squashing-commits) the commits?

Done!

**Comment by justinmayer** [comment]
Many thanks to @rlaboiss for the contribution and to @Lucas-C and @avaris for reviewing. 😄

**Pull request merged**
