### PR TITLE
Plugin inventory and migration status

### PR DESCRIPTION
**Pull request by kdeldycke**
Changes:
* Add migration status of all plugins to keep track of progress.
* Add missing entries.
* Removes duplicate entries.
* Links to hosted plugin sub-folder.
* Links to external plugins (registered here by the way of git submodules).
* Links to migrated plugin repository.
* Re-order entries by their order of appearance in the repository.

I propose to add the following states symbols:
* (blank): Local hosted plugin is still waiting for migration work.
* ⚠️ : Deprecated. Can be safely removed from this repository.
* ❎: Externally maintained plugins that do not need explicit migration from the mono-repo. Migration work need to happen in the original owners' repo. Example: https://github.com/silentlamb/pelican-deadlinks/issues/8
* ✅: Repository has been migrated to https://github.com/pelican-plugins.

That way, once all plugins are marked as greem (either ❎ or ✅), we can safely archive that mono-repo for good.

### CODE REVIEW

**Comment by avaris** [comment]
For some reason, I don't like the wall of ❌s. How about leaving them empty? Also maybe a link to migrated repo on ✅s?

**Comment by kdeldycke** [comment]
@avaris Ah yes, you're probably right. ❌ might be a little bit too aggressive. I'll leave them empty then. Good call on linking ✅ BTW. I'll update my PR.

**Comment by kdeldycke** [comment]
I've finished to inventory all plugins in the mono-repo and their status.

This PR is ready to be merged.

**Comment by justinmayer** [comment]
What if we changed the **Migration** column to an emoji? Maybe a question mark? (❓) That would make that column much narrower while still at least conveying the basic concept of "status", while of course the real explanation is just above. Any thoughts on that?

**Comment by kdeldycke** [comment]
@justinmayer oh, you mean only changing the title of the column from `Migration` to `❓`?

**Comment by avaris** [comment]
Those checkmarks look really subtle on my Windows system, for some reason:
Capture

Here are a few others that look OK here.
✔✖⚠❓❗

**Comment by justinmayer** [comment]
@kdeldycke: Yes, sorry for not being clearer. I did indeed mean changing the column _header_ from from `Migration` to `❓`.

**Comment by kdeldycke** [comment]
@justinmayer found a better emoji: the information sign => ℹ️

@avaris I just replaced all occurrences of `❎` by `✔`.

It's my last round of tweak, after that I'll just follow your instructions if things are not good to you. I'm not that interested in choosing the color of the bikeshed! 😆 I just want to create an authoritative source of the plugin migration progress! 🙂

**Comment by avaris** [comment]
Thank you for doing the work and I know I'm being nitpicky. Don't worry, I can tweak it later.

**Comment by avaris** [comment]
I just added a commit with what I think looks best on most platforms (the ones I can test at least).

**Comment by kdeldycke** [comment]
@avaris aha no worries! And thanks for testing and fixing this on other platforms! 😃 

LGTM, feel free to merge upstream! 👍

**Comment by justinmayer** [comment]
@kdeldycke / @avaris: Many thanks for your work on this. Nice to have a way for us to track this!

**Pull request merged**
