### PR TITLE
new Legacy branch

### PR DESCRIPTION
**Pull request by maphew**
See #1379. PR 2 of 2. 

Changes: 
- Rename Readme to Readme-Legacy, clarify checkout branch instructions, 90% unchanged
- Add the Readme from the new Main branch

### CODE REVIEW

**Comment by maphew** [comment]
This PR says "wants to merge 2 commits into [getpelican:master](https://github.com/getpelican/pelican-plugins) from [maphew:legacy](https://github.com/maphew/pelican-plugins/tree/legacy)" which isn't quite true. It should be merged into a new branch called legacy in the parent repo.

**Comment by maphew** [comment]
To test viability of this legacy branch approach I found and merged 3 PR from the upstream project. All of them featured simple docmentation changes so no testing was necessary. The process was very smooth for the 2 who's source repos were still intact. For the 3rd one I just duplicated the edit and then referenced the original commit and PR in comment.

The guide I followed for merging PR made against the parent fork: https://stackoverflow.com/questions/6022302/how-to-apply-unmerged-upstream-pull-requests-from-other-forks-into-my-fork.

I'm not likely to continue merging upstream PR as I don't have a straightforward means of testing them. (For my own site I'm only using plugins that are following the v4.5+ pip install way.)

**Comment by avaris** [comment]
I'm somewhat puzzled by the intent. 

First of all, you can't change or create branches in the main repo via PRs. That's simply not possible. 

Second, this repo is for legacy plugins only and new style plugins should reside in their own repos (in [pelican-plugins](https://github.com/pelican-plugins) org or personal repos). Eventually (and hopefully), this repo will become obsolete and plugins will migrate to their respective places. So, I don't see the point in restructuring this repo at all.

**Comment by maphew** [comment]
I didn't understand this repo is only for legacy plugins. The restructuring was my attempt to categorize working and non-working plugins as I attempted to get pelican working for myself.  It's been a long time now so I don't know why I was working in/from this repo instead of the pelican-plugins organization. Probably because my starting point in customizing pelican for myself was with themes, which directed me here.

btw, this is off topic but related: the major problem with pelican-plugins org vs this repo is that the org doesn't have a master Readme or index or repo  that gives an overview of the plugin eco system.

**Pull request closed without merging**
