### PR TITLE
Add HackerNews link to Share Post plugin

### PR DESCRIPTION
**Pull request by DEKHTIARJonathan**
New Features:
* Share on Hacker News added

Fixes:
* Documentation Fixed and Updated
* Code Refactored

### CODE REVIEW

**Comment by justinmayer** [comment]
@talha131: Any thoughts on this PR?

**Comment by talha131** [comment]
@justinmayer Sorry, I can't comment, for I have been out of touch from Pelican for quite long.

**Comment by DEKHTIARJonathan** [comment]
@justinmayer and @talha131: Maybe i can give you a working example.

http://www.born2data.com/2017/generative_models-part1.html

image

The logos are not part of the plugin, however, you can try that it works.

**Comment by DEKHTIARJonathan** [comment]
Any news @justinmayer?

**Comment by justinmayer** [comment]
Thanks for the enhancements, Jonathan!

**Pull request merged**
