### PR TITLE
Mathjax configuration option: Allow automatic line breaks

### PR DESCRIPTION
**Pull request by barrysteyn**
Ability for automatic line breaks to be controlled in the plugin configuration

### CODE REVIEW

**Comment by justinmayer** [comment]
Perhaps document the new setting in the plugin's ReadMe?

**Comment by barrysteyn** [comment]
Oops, that's stupid of me. I'll do it asap

**Comment by barrysteyn** [comment]
Okay, its done

**Comment by justinmayer** [comment]
Cool. Thanks for the enhancement!

**Pull request merged**
