### PR TITLE
photos: Refactor of photos, bug fixes, additional features

### LINKED ISSUE #546: Howto quickly create exif.txt
Maybe add in the Readme how to quickly create exif.txt : 
e.g. : 

    #!/usr/bin/bash
    FILENAME=$(exiftool -common $1 | grep 'File Name' | cut -d\: -f2 |tr -d \ )
    CAMERA=$(exiftool -common $1 | grep 'Camera' | cut -d\: -f2 |tr -d \ )
    LENGTH=$(exiftool -common $1 | grep 'Length' | cut -d\: -f2 |tr -d \ )
    APERTURE=$(exiftool -common $1 | grep 'Aperture' | cut -d\: -f2 |tr -d \ )
    SPEED=$(exiftool -common $1 | grep 'Speed' | cut -d\: -f2 |tr -d \ )s
    ISO=$(exiftool -common $1 | grep 'ISO' | cut -d\: -f2 |tr -d \ )
    LENS=$(exiftool $1 | grep 'Lens Model' | cut -d\: -f2 |cut -d\  -f2)
    echo "$FILENAME: $CAMERA + $LENS ― $LENGTH - f/$APERTURE - $SPEED - ISO $ISO"

Then someting like `touch exif.txt && find ./ -type f -name '*.jpg' -exec ~/exif_extract.sh {} \; >> exif.txt`

If you ask me, I'll write a more complete python script to generate the `exif.txt`.

### LINKED ISSUE #723: [Photos] Current documentation does not work
I just set up the Photos Plugin with my blog. When trying to adjust the template as stated in the README file pelican produed an error due to the fact that
article.photo_gallery does not, as mentioned, hold 5-tuples for each photo inside the gallery associated to the article but a tuple of the gallery name in its first element and a list with the 5-tuples describing the pictures in its second element.

I changed the code added to the article.html template file as follows:
```
{% if article.photo_gallery %}
  <div class="gallery">
    {% for gallery in article.photo_gallery %}
      {% for name, photo, thumb, exif, caption in gallery[1] %}
        <a href="{{ SITEURL }}/{{ photo }}" title="{{ name }}" exif="{{ exif }}" caption="{{ caption }}"><img src="{{ SITEURL }}/{{ thumb }}"></a>
      {% endfor %}
    {% endfor %}
  </div>
{% endif %}
```
As I am not yet very familiar with Pelican, Plugins, and theming, this solution works but does not feel to be the correct one. I am sure that there is a more correct way of doing it.

Anyway, the documentation should probably be corrected to reflect that problem.

### PR DESCRIPTION
**Pull request by bnice5000**
Fixes #723 
Fixes #546
Incorporated pull request #733 
Incorporated discussion on commit 272fcb5

This plugin also adds the ability to add watermarks to images.

### CODE REVIEW

**Comment by justinmayer** [comment]
Thanks for the contribution, Brian. Would you please [rebase & squash your commits](https://github.com/getpelican/pelican/wiki/Git-Tips#squashing-commits)?

**Comment by bnice5000** [comment]
@justinmayer I believe I did that correctly. Not a huge user of git. Let me know if there is anything I need to fix.

**Comment by justinmayer** [comment]
Squash seems to have been successful. Nicely done.

Only issue remaining is the commit message, which appears to have some redundant info in it:

<details>
```
Refactored photos. Added watermark and blacklist. Fixed some bugs. Updated documentation

Updated documentation to include multigalleries.

Updated documentation to include multigalleries.

Updated documentation to include multigalleries.

Updated documentation to include pillow

Fixed issue with images that had no alpha channel. New feature that dynamically sizes image as part of watermark.

Fixed issue with images that had no alpha channel. New feature that dynamically sizes image as part of watermark.
```
</details>

**Comment by bnice5000** [comment]
@justinmayer I think I fixed the redundant commit messages. I really need to switch the default git editor to emacs. I can never remember the vim keyboard sequences.

**Comment by justinmayer** [comment]
Looks good. Thanks!

**Comment by fufler** [comment]
@bnice5000  @justinmayer

This update made photos plugin incompatible with Python 3. Please consider applying the following patch to fix the issue:

```diff
diff --git a/photos/photos.py b/photos/photos.py
index ba5c8cf..bf1ba2a 100644
--- a/photos/photos.py
+++ b/photos/photos.py
@@ -6,6 +6,7 @@ import logging
 import os
 import pprint
 import re
+import sys
 
 from pelican.generators import ArticlesGenerator
 from pelican.generators import PagesGenerator
@@ -235,7 +236,7 @@ def detect_content(content):
 def galleries_string_decompose(gallery_string):
     splitter_regex = re.compile(r'[\s,]*?({photo}|{filename})')
     title_regex = re.compile(r'{(.+)}')
-    galleries = map(unicode.strip, filter(None, splitter_regex.split(gallery_string)))
+    galleries = map(unicode.strip if sys.version_info.major == 2 else str.strip, filter(None, splitter_regex.split(gallery_string)))
     galleries = [gallery[1:] if gallery.startswith('/') else gallery for gallery in galleries]
     if len(galleries) % 2 == 0 and u' ' not in galleries:
         galleries = zip(zip(['type'] * len(galleries[0::2]), galleries[0::2]), zip(['location'] * len(galleries[0::2]), galleries[1::2]))
```

**Pull request merged**
