### PR TITLE
Gravatar plugin > Standardize quotation marks

### PR DESCRIPTION
**Pull request by dakerfp**

### CODE REVIEW

**Comment by justinmayer** [comment]
Not sure how this is "standardizing"; the existing style seems to be consistent with [generally accepted practice](http://stackoverflow.com/a/56190).

**Comment by dakerfp** [comment]
It is consistent with the practice, but is not consistent with itself: 
metadata["author_gravatar"]
metadata['email']

**Comment by justinmayer** [comment]
You are quite right -- somehow I read it backwards, as if you were making the change in the other direction. #notenoughcoffee

Thanks for the fix!

**Comment by dakerfp** [comment]
You're welcome.

**Pull request merged**
