### PR TITLE
Allow tipue_search to index tags of content (in addition to category)

### PR DESCRIPTION
**Pull request by Siltaar**

### CODE REVIEW

**Comment by jorgesumle** [comment]
Can you please improve the license header from the JavaScript file? I would like it to be detected as free software by LibreJS, see section *3.2.4 Stylized comment* from the article "Setting Your JavaScript Free" or have a look at [its documentation](https://www.gnu.org/software/librejs/manual/).

**Comment by Siltaar** [comment]
Should be good this way.

**Comment by kdeldycke** [comment]
For the record, the canonical `tipue_search` plugin is about to be moved to its own repository at: https://github.com/pelican-plugins/tipue-search.

I guess this PR can be moved in the new repository if it is still current.

**Comment by Siltaar** [comment]
This got lost, and was confusing with 2 things in the same PR.
I'll make separate PRs.

**Pull request closed without merging**
