### PR TITLE
Fix sitemap plugin to look for index#.html files (if pagination is on)

### PR DESCRIPTION
**Pull request by Vincent-C**
The current sitemap plugin only adds index.html to the sitemap, but if the user has pagination enabled (which generates index2.html, index3.html, etc.), then these additional index files don't get added to the sitemap.

I've quickly hacked together a solution that works, although I don't think hardcoding "100" in there is the right thing to do. Suggestions?

### CODE REVIEW

**Comment by mknecht** [comment]
Hey, what would have to change so that this fix gets included?

**Comment by justinmayer** [comment]
1. a better solution, preferably, than hardcoding "100"
2. clean-up into a single commit

**Comment by kdeldycke** [comment]
This proposed fix is outdated. `sitemap` code has been refactored in commit https://github.com/pelican-plugins/sitemap/commit/c8cf56251bdb6c1e226d9408f620d22b574e2ac0 to make it more sensitive to the site configuration.

I guess this PR can be closed.

**Comment by justinmayer** [comment]
Thanks, Kevin!

**Pull request closed without merging**
